# Generated by Django 3.2.20 on 2023-08-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_code',
            field=models.CharField(default='', max_length=5, unique=True),
        ),
    ]
