# Generated by Django 3.2.20 on 2023-08-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0003_auto_20230807_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='caption',
            field=models.TextField(null=True),
        ),
    ]
