# Generated by Django 3.2.20 on 2023-08-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0005_auto_20230807_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='company_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
